In [4]:
products = [
    {"product_id": "P001", "product_name": "Inspiron 15", "category": "Laptop", "brand": "Dell", "price": 55000, "rating": 4.2, "stock": 15, "discount": 10},
    {"product_id": "P002", "product_name": "IdeaPad Slim 3", "category": "Laptop", "brand": "Lenovo", "price": 48000, "rating": 4.1, "stock": 20, "discount": 12},
    {"product_id": "P003", "product_name": "Pavilion 14", "category": "Laptop", "brand": "HP", "price": 62000, "rating": 4.3, "stock": 12, "discount": 8},
    {"product_id": "P004", "product_name": "MacBook Air M2", "category": "Laptop", "brand": "Apple", "price": 95000, "rating": 4.7, "stock": 8, "discount": 5},
    {"product_id": "P005", "product_name": "VivoBook 15", "category": "Laptop", "brand": "Asus", "price": 52000, "rating": 4.2, "stock": 18, "discount": 15},
    {"product_id": "P006", "product_name": "Galaxy S24", "category": "Mobile", "brand": "Samsung", "price": 72000, "rating": 4.6, "stock": 10, "discount": 7},
    {"product_id": "P007", "product_name": "iPhone 15", "category": "Mobile", "brand": "Apple", "price": 70000, "rating": 4.7, "stock": 14, "discount": 6},
    {"product_id": "P008", "product_name": "OnePlus 12", "category": "Mobile", "brand": "OnePlus", "price": 64000, "rating": 4.5, "stock": 16, "discount": 10},
    {"product_id": "P009", "product_name": "Pixel 8", "category": "Mobile", "brand": "Google", "price": 58000, "rating": 4.4, "stock": 9, "discount": 9},
    {"product_id": "P010", "product_name": "Nothing Phone 2", "category": "Mobile", "brand": "Nothing", "price": 42000, "rating": 4.3, "stock": 22, "discount": 13},

    {"product_id": "P011", "product_name": "WH-1000XM5", "category": "Headphones", "brand": "Sony", "price": 29990, "rating": 4.8, "stock": 11, "discount": 10},
    {"product_id": "P012", "product_name": "AirPods Pro 2", "category": "Headphones", "brand": "Apple", "price": 24900, "rating": 4.7, "stock": 18, "discount": 5},
    {"product_id": "P013", "product_name": "QuietComfort 45", "category": "Headphones", "brand": "Bose", "price": 28000, "rating": 4.6, "stock": 7, "discount": 12},
    {"product_id": "P014", "product_name": "JBL Tune 760NC", "category": "Headphones", "brand": "JBL", "price": 5999, "rating": 4.3, "stock": 25, "discount": 20},
    {"product_id": "P015", "product_name": "Sennheiser HD 450", "category": "Headphones", "brand": "Sennheiser", "price": 12999, "rating": 4.5, "stock": 13, "discount": 15},

    {"product_id": "P016", "product_name": "MX Keys", "category": "Keyboard", "brand": "Logitech", "price": 8999, "rating": 4.6, "stock": 20, "discount": 10},
    {"product_id": "P017", "product_name": "K2 Mechanical", "category": "Keyboard", "brand": "Keychron", "price": 9500, "rating": 4.5, "stock": 9, "discount": 8},
    {"product_id": "P018", "product_name": "MK850", "category": "Keyboard", "brand": "Logitech", "price": 7499, "rating": 4.4, "stock": 15, "discount": 12},
    {"product_id": "P019", "product_name": "BlackWidow V3", "category": "Keyboard", "brand": "Razer", "price": 10999, "rating": 4.6, "stock": 10, "discount": 15},
    {"product_id": "P020", "product_name": "Alloy Origins", "category": "Keyboard", "brand": "HyperX", "price": 8990, "rating": 4.5, "stock": 17, "discount": 10},

    {"product_id": "P021", "product_name": "UltraGear 27", "category": "Monitor", "brand": "LG", "price": 28000, "rating": 4.5, "stock": 8, "discount": 12},
    {"product_id": "P022", "product_name": "Odyssey G5", "category": "Monitor", "brand": "Samsung", "price": 32000, "rating": 4.6, "stock": 6, "discount": 10},
    {"product_id": "P023", "product_name": "VG27AQ", "category": "Monitor", "brand": "Asus", "price": 35000, "rating": 4.7, "stock": 9, "discount": 8},
    {"product_id": "P024", "product_name": "S2721D", "category": "Monitor", "brand": "Dell", "price": 22000, "rating": 4.4, "stock": 14, "discount": 15},
    {"product_id": "P025", "product_name": "M27Q", "category": "Monitor", "brand": "Gigabyte", "price": 26000, "rating": 4.5, "stock": 12, "discount": 10},

    {"product_id": "P026", "product_name": "iPad Air", "category": "Tablet", "brand": "Apple", "price": 59900, "rating": 4.7, "stock": 10, "discount": 5},
    {"product_id": "P027", "product_name": "Galaxy Tab S9", "category": "Tablet", "brand": "Samsung", "price": 72000, "rating": 4.6, "stock": 7, "discount": 10},
    {"product_id": "P028", "product_name": "Pad 6", "category": "Tablet", "brand": "Xiaomi", "price": 29999, "rating": 4.5, "stock": 18, "discount": 12},
    {"product_id": "P029", "product_name": "Tab P12", "category": "Tablet", "brand": "Lenovo", "price": 32999, "rating": 4.4, "stock": 13, "discount": 15},
    {"product_id": "P030", "product_name": "OnePlus Pad", "category": "Tablet", "brand": "OnePlus", "price": 37999, "rating": 4.5, "stock": 11, "discount": 8},

    {"product_id": "P031", "product_name": "Wireless Mouse", "category": "Accessories", "brand": "Logitech", "price": 1299, "rating": 4.3, "stock": 40, "discount": 20},
    {"product_id": "P032", "product_name": "Laptop Stand", "category": "Accessories", "brand": "Portronics", "price": 1499, "rating": 4.2, "stock": 30, "discount": 15},
    {"product_id": "P033", "product_name": "USB-C Hub", "category": "Accessories", "brand": "Anker", "price": 3499, "rating": 4.5, "stock": 25, "discount": 10},
    {"product_id": "P034", "product_name": "Webcam C920", "category": "Accessories", "brand": "Logitech", "price": 6999, "rating": 4.6, "stock": 14, "discount": 12},
    {"product_id": "P035", "product_name": "HDMI Cable", "category": "Accessories", "brand": "AmazonBasics", "price": 799, "rating": 4.4, "stock": 50, "discount": 25},
    {"product_id": "P036", "product_name": "Power Bank 20000", "category": "Accessories", "brand": "Ambrane", "price": 1999, "rating": 4.3, "stock": 35, "discount": 18},
    {"product_id": "P037", "product_name": "Bluetooth Mouse", "category": "Accessories", "brand": "HP", "price": 999, "rating": 4.1, "stock": 45, "discount": 20},
    {"product_id": "P038", "product_name": "Laptop Sleeve", "category": "Accessories", "brand": "Targus", "price": 1799, "rating": 4.2, "stock": 28, "discount": 15},
    {"product_id": "P039", "product_name": "Wireless Charger", "category": "Accessories", "brand": "Belkin", "price": 2999, "rating": 4.4, "stock": 16, "discount": 10},
    {"product_id": "P040", "product_name": "Cooling Pad", "category": "Accessories", "brand": "Cooler Master", "price": 2499, "rating": 4.3, "stock": 20, "discount": 12},

    {"product_id": "P041", "product_name": "MacBook Pro M3", "category": "Laptop", "brand": "Apple", "price": 169000, "rating": 4.9, "stock": 5, "discount": 4},
    {"product_id": "P042", "product_name": "ThinkPad E14", "category": "Laptop", "brand": "Lenovo", "price": 68000, "rating": 4.4, "stock": 11, "discount": 10},
    {"product_id": "P043", "product_name": "ROG Strix G16", "category": "Laptop", "brand": "Asus", "price": 125000, "rating": 4.7, "stock": 6, "discount": 8},
    {"product_id": "P044", "product_name": "XPS 13", "category": "Laptop", "brand": "Dell", "price": 115000, "rating": 4.6, "stock": 7, "discount": 7},
    {"product_id": "P045", "product_name": "Envy x360", "category": "Laptop", "brand": "HP", "price": 82000, "rating": 4.5, "stock": 10, "discount": 12},

    {"product_id": "P046", "product_name": "iPhone 15 Pro", "category": "Mobile", "brand": "Apple", "price": 129000, "rating": 4.8, "stock": 6, "discount": 4},
    {"product_id": "P047", "product_name": "Galaxy S24 Ultra", "category": "Mobile", "brand": "Samsung", "price": 130000, "rating": 4.8, "stock": 5, "discount": 6},
    {"product_id": "P048", "product_name": "Nord CE 4", "category": "Mobile", "brand": "OnePlus", "price": 24999, "rating": 4.3, "stock": 25, "discount": 15},
    {"product_id": "P049", "product_name": "Moto Edge 50", "category": "Mobile", "brand": "Motorola", "price": 29999, "rating": 4.4, "stock": 19, "discount": 12},
    {"product_id": "P050", "product_name": "Redmi Note 13", "category": "Mobile", "brand": "Xiaomi", "price": 18999, "rating": 4.2, "stock": 30, "discount": 18}
]

In [2]:
import csv

In [5]:
with open("product_dataset.csv" , "w" , newline="") as file:
    writer=csv.DictWriter(file,fieldnames=products[0].keys())
    writer.writeheader()
    writer.writerows(products)
print("product_dataset.csv created successfully")

product_dataset.csv created successfully

In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Eswar\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Eswar\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd
df=pd.read_csv("product_dataset.csv")

In [12]:
df

,product_id,product_name,category,brand,price,rating,stock,discount
0,P001,Inspiron 15,Laptop,Dell,55000,4.2,15,10
1,P002,IdeaPad Slim 3,Laptop,Lenovo,48000,4.1,20,12
2,P003,Pavilion 14,Laptop,HP,62000,4.3,12,8
3,P004,MacBook Air M2,Laptop,Apple,95000,4.7,8,5
4,P005,VivoBook 15,Laptop,Asus,52000,4.2,18,15
5,P006,Galaxy S24,Mobile,Samsung,72000,4.6,10,7
6,P007,iPhone 15,Mobile,Apple,70000,4.7,14,6
7,P008,OnePlus 12,Mobile,OnePlus,64000,4.5,16,10
8,P009,Pixel 8,Mobile,Google,58000,4.4,9,9
9,P010,Nothing Phone 2,Mobile,Nothing,42000,4.3,22,13
10,P011,WH-1000XM5,Headphones,Sony,29990,4.8,11,10
11,P012,AirPods Pro 2,Headphones,Apple,24900,4.7,18,5
12,P013,QuietComfort 45,Headphones,Bose,28000,4.6,7,12
13,P014,JBL Tune 760NC,Headphones,JBL,5999,4.3,25,20
14,P015,Sennheiser HD 450,Headphones,Sennheiser,12999,4.5,13,15
15,P016,MX Keys,Keyboard,Logitech,8999,4.6,20,10
16,P017,K2 Mechanical,Keyboard,Keychron,9500,4.5,9,8
17,P018,MK850,Keyboard,Logitech,7499,4.4,15,12
18,P019,BlackWidow V3,Keyboard,Razer,10999,4.6,10,15
19,P020,Alloy Origins,Keyboard,HyperX,8990,4.5,17,10
20,P021,UltraGear 27,Monitor,LG,28000,4.5,8,12
21,P022,Odyssey G5,Monitor,Samsung,32000,4.6,6,10
22,P023,VG27AQ,Monitor,Asus,35000,4.7,9,8
23,P024,S2721D,Monitor,Dell,22000,4.4,14,15
24,P025,M27Q,Monitor,Gigabyte,26000,4.5,12,10
25,P026,iPad Air,Tablet,Apple,59900,4.7,10,5
26,P027,Galaxy Tab S9,Tablet,Samsung,72000,4.6,7,10
27,P028,Pad 6,Tablet,Xiaomi,29999,4.5,18,12
28,P029,Tab P12,Tablet,Lenovo,32999,4.4,13,15
29,P030,OnePlus Pad,Tablet,OnePlus,37999,4.5,11,8
30,P031,Wireless Mouse,Accessories,Logitech,1299,4.3,40,20
31,P032,Laptop Stand,Accessories,Portronics,1499,4.2,30,15
32,P033,USB-C Hub,Accessories,Anker,3499,4.5,25,10
33,P034,Webcam C920,Accessories,Logitech,6999,4.6,14,12
34,P035,HDMI Cable,Accessories,AmazonBasics,799,4.4,50,25
35,P036,Power Bank 20000,Accessories,Ambrane,1999,4.3,35,18
36,P037,Bluetooth Mouse,Accessories,HP,999,4.1,45,20
37,P038,Laptop Sleeve,Accessories,Targus,1799,4.2,28,15
38,P039,Wireless Charger,Accessories,Belkin,2999,4.4,16,10
39,P040,Cooling Pad,Accessories,Cooler Master,2499,4.3,20,12
40,P041,MacBook Pro M3,Laptop,Apple,169000,4.9,5,4
41,P042,ThinkPad E14,Laptop,Lenovo,68000,4.4,11,10
42,P043,ROG Strix G16,Laptop,Asus,125000,4.7,6,8
43,P044,XPS 13,Laptop,Dell,115000,4.6,7,7
44,P045,Envy x360,Laptop,HP,82000,4.5,10,12
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18

In [18]:
df.head()

  product_id    product_name category   brand  price  rating  stock  discount
0       P001     Inspiron 15   Laptop    Dell  55000     4.2     15        10
1       P002  IdeaPad Slim 3   Laptop  Lenovo  48000     4.1     20        12
2       P003     Pavilion 14   Laptop      HP  62000     4.3     12         8
3       P004  MacBook Air M2   Laptop   Apple  95000     4.7      8         5
4       P005     VivoBook 15   Laptop    Asus  52000     4.2     18        15

In [19]:
df.tail()

,product_id,product_name,category,brand,price,rating,stock,discount
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18

In [20]:
df.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'rating',
       'stock', 'discount'],
      dtype='str')

In [21]:
df.dtypes

product_id          str
product_name        str
category            str
brand               str
price             int64
rating          float64
stock             int64
discount          int64
dtype: object

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    50 non-null     str
 1   product_name  50 non-null     str
 2   category      50 non-null     str
 3   brand         50 non-null     str
 4   price         50 non-null     int64
 5   rating        50 non-null     float64
 6   stock         50 non-null     int64
 7   discount      50 non-null     int64
dtypes: float64(1), int64(3), str(4)
memory usage: 3.3 KB

In [23]:
df.describe()

              price    rating      stock   discount
count      50.00000  50.00000  50.000000  50.000000
mean    41163.18000   4.47600  16.480000  11.400000
std     40178.22515   0.19437  10.252406   4.558016
min       799.00000   4.10000   5.000000   4.000000
25%      8992.25000   4.30000   9.250000   8.000000
50%     29994.50000   4.50000  14.000000  10.000000
75%     61475.00000   4.60000  20.000000  15.000000
max    169000.00000   4.90000  50.000000  25.000000

In [24]:
df.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
stock           0
discount        0
dtype: int64

In [31]:
len(df)

50

In [33]:
df.shape[0]

50

In [34]:
df["category"].unique()

<StringArray>
[     'Laptop',      'Mobile',  'Headphones',    'Keyboard',     'Monitor',
      'Tablet', 'Accessories']
Length: 7, dtype: str

In [35]:
df["brand"].unique()

<StringArray>
[         'Dell',        'Lenovo',            'HP',         'Apple',
          'Asus',       'Samsung',       'OnePlus',        'Google',
       'Nothing',          'Sony',          'Bose',           'JBL',
    'Sennheiser',      'Logitech',      'Keychron',         'Razer',
        'HyperX',            'LG',      'Gigabyte',        'Xiaomi',
    'Portronics',         'Anker',  'AmazonBasics',       'Ambrane',
        'Targus',        'Belkin', 'Cooler Master',      'Motorola']
Length: 28, dtype: str

In [39]:
df["category"].value_counts()

category
Laptop         10
Mobile         10
Accessories    10
Headphones      5
Keyboard        5
Monitor         5
Tablet          5
Name: count, dtype: int64

In [40]:
df["price"].mean()

np.float64(41163.18)

In [49]:
df.sort_values("price",ascending=False)["product_name"].iloc[0]

'MacBook Pro M3'

In [50]:
df.sort_values("price")["product_name"].iloc[0]

'HDMI Cable'

In [51]:
df[df["price"]>50000]["product_name"]

0          Inspiron 15
2          Pavilion 14
3       MacBook Air M2
4          VivoBook 15
5           Galaxy S24
6            iPhone 15
7           OnePlus 12
8              Pixel 8
25            iPad Air
26       Galaxy Tab S9
40      MacBook Pro M3
41        ThinkPad E14
42       ROG Strix G16
43              XPS 13
44           Envy x360
45       iPhone 15 Pro
46    Galaxy S24 Ultra
Name: product_name, dtype: str

In [52]:
df[df["rating"]>4]["product_name"]

0           Inspiron 15
1        IdeaPad Slim 3
2           Pavilion 14
3        MacBook Air M2
4           VivoBook 15
5            Galaxy S24
6             iPhone 15
7            OnePlus 12
8               Pixel 8
9       Nothing Phone 2
10           WH-1000XM5
11        AirPods Pro 2
12      QuietComfort 45
13       JBL Tune 760NC
14    Sennheiser HD 450
15              MX Keys
16        K2 Mechanical
17                MK850
18        BlackWidow V3
19        Alloy Origins
20         UltraGear 27
21           Odyssey G5
22               VG27AQ
23               S2721D
24                 M27Q
25             iPad Air
26        Galaxy Tab S9
27                Pad 6
28              Tab P12
29          OnePlus Pad
30       Wireless Mouse
31         Laptop Stand
32            USB-C Hub
33          Webcam C920
34           HDMI Cable
35     Power Bank 20000
36      Bluetooth Mouse
37        Laptop Sleeve
38     Wireless Charger
39          Cooling Pad
40       MacBook Pro M3
41         ThinkPad E14
42        ROG Strix G16
43               XPS 13
44            Envy x360
45        iPhone 15 Pro
46     Galaxy S24 Ultra
47            Nord CE 4
48         Moto Edge 50
49        Redmi Note 13
Name: product_name, dtype: str

In [53]:
df.sort_values("price")

,product_id,product_name,category,brand,price,rating,stock,discount
34,P035,HDMI Cable,Accessories,AmazonBasics,799,4.4,50,25
36,P037,Bluetooth Mouse,Accessories,HP,999,4.1,45,20
30,P031,Wireless Mouse,Accessories,Logitech,1299,4.3,40,20
31,P032,Laptop Stand,Accessories,Portronics,1499,4.2,30,15
37,P038,Laptop Sleeve,Accessories,Targus,1799,4.2,28,15
35,P036,Power Bank 20000,Accessories,Ambrane,1999,4.3,35,18
39,P040,Cooling Pad,Accessories,Cooler Master,2499,4.3,20,12
38,P039,Wireless Charger,Accessories,Belkin,2999,4.4,16,10
32,P033,USB-C Hub,Accessories,Anker,3499,4.5,25,10
13,P014,JBL Tune 760NC,Headphones,JBL,5999,4.3,25,20
33,P034,Webcam C920,Accessories,Logitech,6999,4.6,14,12
17,P018,MK850,Keyboard,Logitech,7499,4.4,15,12
19,P020,Alloy Origins,Keyboard,HyperX,8990,4.5,17,10
15,P016,MX Keys,Keyboard,Logitech,8999,4.6,20,10
16,P017,K2 Mechanical,Keyboard,Keychron,9500,4.5,9,8
18,P019,BlackWidow V3,Keyboard,Razer,10999,4.6,10,15
14,P015,Sennheiser HD 450,Headphones,Sennheiser,12999,4.5,13,15
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18
23,P024,S2721D,Monitor,Dell,22000,4.4,14,15
11,P012,AirPods Pro 2,Headphones,Apple,24900,4.7,18,5
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15
24,P025,M27Q,Monitor,Gigabyte,26000,4.5,12,10
12,P013,QuietComfort 45,Headphones,Bose,28000,4.6,7,12
20,P021,UltraGear 27,Monitor,LG,28000,4.5,8,12
10,P011,WH-1000XM5,Headphones,Sony,29990,4.8,11,10
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12
27,P028,Pad 6,Tablet,Xiaomi,29999,4.5,18,12
21,P022,Odyssey G5,Monitor,Samsung,32000,4.6,6,10
28,P029,Tab P12,Tablet,Lenovo,32999,4.4,13,15
22,P023,VG27AQ,Monitor,Asus,35000,4.7,9,8
29,P030,OnePlus Pad,Tablet,OnePlus,37999,4.5,11,8
9,P010,Nothing Phone 2,Mobile,Nothing,42000,4.3,22,13
1,P002,IdeaPad Slim 3,Laptop,Lenovo,48000,4.1,20,12
4,P005,VivoBook 15,Laptop,Asus,52000,4.2,18,15
0,P001,Inspiron 15,Laptop,Dell,55000,4.2,15,10
8,P009,Pixel 8,Mobile,Google,58000,4.4,9,9
25,P026,iPad Air,Tablet,Apple,59900,4.7,10,5
2,P003,Pavilion 14,Laptop,HP,62000,4.3,12,8
7,P008,OnePlus 12,Mobile,OnePlus,64000,4.5,16,10
41,P042,ThinkPad E14,Laptop,Lenovo,68000,4.4,11,10
6,P007,iPhone 15,Mobile,Apple,70000,4.7,14,6
5,P006,Galaxy S24,Mobile,Samsung,72000,4.6,10,7
26,P027,Galaxy Tab S9,Tablet,Samsung,72000,4.6,7,10
44,P045,Envy x360,Laptop,HP,82000,4.5,10,12
3,P004,MacBook Air M2,Laptop,Apple,95000,4.7,8,5
43,P044,XPS 13,Laptop,Dell,115000,4.6,7,7
42,P043,ROG Strix G16,Laptop,Asus,125000,4.7,6,8
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6
40,P041,MacBook Pro M3,Laptop,Apple,169000,4.9,5,4

In [54]:
df.sort_values("rating")

,product_id,product_name,category,brand,price,rating,stock,discount
1,P002,IdeaPad Slim 3,Laptop,Lenovo,48000,4.1,20,12
36,P037,Bluetooth Mouse,Accessories,HP,999,4.1,45,20
4,P005,VivoBook 15,Laptop,Asus,52000,4.2,18,15
0,P001,Inspiron 15,Laptop,Dell,55000,4.2,15,10
37,P038,Laptop Sleeve,Accessories,Targus,1799,4.2,28,15
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18
31,P032,Laptop Stand,Accessories,Portronics,1499,4.2,30,15
13,P014,JBL Tune 760NC,Headphones,JBL,5999,4.3,25,20
35,P036,Power Bank 20000,Accessories,Ambrane,1999,4.3,35,18
9,P010,Nothing Phone 2,Mobile,Nothing,42000,4.3,22,13
39,P040,Cooling Pad,Accessories,Cooler Master,2499,4.3,20,12
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15
30,P031,Wireless Mouse,Accessories,Logitech,1299,4.3,40,20
2,P003,Pavilion 14,Laptop,HP,62000,4.3,12,8
23,P024,S2721D,Monitor,Dell,22000,4.4,14,15
17,P018,MK850,Keyboard,Logitech,7499,4.4,15,12
34,P035,HDMI Cable,Accessories,AmazonBasics,799,4.4,50,25
41,P042,ThinkPad E14,Laptop,Lenovo,68000,4.4,11,10
8,P009,Pixel 8,Mobile,Google,58000,4.4,9,9
28,P029,Tab P12,Tablet,Lenovo,32999,4.4,13,15
38,P039,Wireless Charger,Accessories,Belkin,2999,4.4,16,10
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12
32,P033,USB-C Hub,Accessories,Anker,3499,4.5,25,10
44,P045,Envy x360,Laptop,HP,82000,4.5,10,12
27,P028,Pad 6,Tablet,Xiaomi,29999,4.5,18,12
29,P030,OnePlus Pad,Tablet,OnePlus,37999,4.5,11,8
24,P025,M27Q,Monitor,Gigabyte,26000,4.5,12,10
16,P017,K2 Mechanical,Keyboard,Keychron,9500,4.5,9,8
14,P015,Sennheiser HD 450,Headphones,Sennheiser,12999,4.5,13,15
19,P020,Alloy Origins,Keyboard,HyperX,8990,4.5,17,10
20,P021,UltraGear 27,Monitor,LG,28000,4.5,8,12
7,P008,OnePlus 12,Mobile,OnePlus,64000,4.5,16,10
18,P019,BlackWidow V3,Keyboard,Razer,10999,4.6,10,15
12,P013,QuietComfort 45,Headphones,Bose,28000,4.6,7,12
5,P006,Galaxy S24,Mobile,Samsung,72000,4.6,10,7
15,P016,MX Keys,Keyboard,Logitech,8999,4.6,20,10
33,P034,Webcam C920,Accessories,Logitech,6999,4.6,14,12
43,P044,XPS 13,Laptop,Dell,115000,4.6,7,7
21,P022,Odyssey G5,Monitor,Samsung,32000,4.6,6,10
26,P027,Galaxy Tab S9,Tablet,Samsung,72000,4.6,7,10
6,P007,iPhone 15,Mobile,Apple,70000,4.7,14,6
25,P026,iPad Air,Tablet,Apple,59900,4.7,10,5
11,P012,AirPods Pro 2,Headphones,Apple,24900,4.7,18,5
22,P023,VG27AQ,Monitor,Asus,35000,4.7,9,8
42,P043,ROG Strix G16,Laptop,Asus,125000,4.7,6,8
3,P004,MacBook Air M2,Laptop,Apple,95000,4.7,8,5
10,P011,WH-1000XM5,Headphones,Sony,29990,4.8,11,10
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6
40,P041,MacBook Pro M3,Laptop,Apple,169000,4.9,5,4

In [55]:
df[df["stock"]<10]["product_name"]

3       MacBook Air M2
8              Pixel 8
12     QuietComfort 45
16       K2 Mechanical
20        UltraGear 27
21          Odyssey G5
22              VG27AQ
26       Galaxy Tab S9
40      MacBook Pro M3
42       ROG Strix G16
43              XPS 13
45       iPhone 15 Pro
46    Galaxy S24 Ultra
Name: product_name, dtype: str

In [58]:
df["discount_amount"]=(df["price"]*df["discount"]/100)

In [60]:
df["finl_price"]=df["price"]-(df["price"]*df["discount"]/100)

In [61]:
df

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount,finl_price
0,P001,Inspiron 15,Laptop,Dell,55000,4.2,15,10,5500.00,49500.00
1,P002,IdeaPad Slim 3,Laptop,Lenovo,48000,4.1,20,12,5760.00,42240.00
2,P003,Pavilion 14,Laptop,HP,62000,4.3,12,8,4960.00,57040.00
3,P004,MacBook Air M2,Laptop,Apple,95000,4.7,8,5,4750.00,90250.00
4,P005,VivoBook 15,Laptop,Asus,52000,4.2,18,15,7800.00,44200.00
5,P006,Galaxy S24,Mobile,Samsung,72000,4.6,10,7,5040.00,66960.00
6,P007,iPhone 15,Mobile,Apple,70000,4.7,14,6,4200.00,65800.00
7,P008,OnePlus 12,Mobile,OnePlus,64000,4.5,16,10,6400.00,57600.00
8,P009,Pixel 8,Mobile,Google,58000,4.4,9,9,5220.00,52780.00
9,P010,Nothing Phone 2,Mobile,Nothing,42000,4.3,22,13,5460.00,36540.00
10,P011,WH-1000XM5,Headphones,Sony,29990,4.8,11,10,2999.00,26991.00
11,P012,AirPods Pro 2,Headphones,Apple,24900,4.7,18,5,1245.00,23655.00
12,P013,QuietComfort 45,Headphones,Bose,28000,4.6,7,12,3360.00,24640.00
13,P014,JBL Tune 760NC,Headphones,JBL,5999,4.3,25,20,1199.80,4799.20
14,P015,Sennheiser HD 450,Headphones,Sennheiser,12999,4.5,13,15,1949.85,11049.15
15,P016,MX Keys,Keyboard,Logitech,8999,4.6,20,10,899.90,8099.10
16,P017,K2 Mechanical,Keyboard,Keychron,9500,4.5,9,8,760.00,8740.00
17,P018,MK850,Keyboard,Logitech,7499,4.4,15,12,899.88,6599.12
18,P019,BlackWidow V3,Keyboard,Razer,10999,4.6,10,15,1649.85,9349.15
19,P020,Alloy Origins,Keyboard,HyperX,8990,4.5,17,10,899.00,8091.00
20,P021,UltraGear 27,Monitor,LG,28000,4.5,8,12,3360.00,24640.00
21,P022,Odyssey G5,Monitor,Samsung,32000,4.6,6,10,3200.00,28800.00
22,P023,VG27AQ,Monitor,Asus,35000,4.7,9,8,2800.00,32200.00
23,P024,S2721D,Monitor,Dell,22000,4.4,14,15,3300.00,18700.00
24,P025,M27Q,Monitor,Gigabyte,26000,4.5,12,10,2600.00,23400.00
25,P026,iPad Air,Tablet,Apple,59900,4.7,10,5,2995.00,56905.00
26,P027,Galaxy Tab S9,Tablet,Samsung,72000,4.6,7,10,7200.00,64800.00
27,P028,Pad 6,Tablet,Xiaomi,29999,4.5,18,12,3599.88,26399.12
28,P029,Tab P12,Tablet,Lenovo,32999,4.4,13,15,4949.85,28049.15
29,P030,OnePlus Pad,Tablet,OnePlus,37999,4.5,11,8,3039.92,34959.08
30,P031,Wireless Mouse,Accessories,Logitech,1299,4.3,40,20,259.80,1039.20
31,P032,Laptop Stand,Accessories,Portronics,1499,4.2,30,15,224.85,1274.15
32,P033,USB-C Hub,Accessories,Anker,3499,4.5,25,10,349.90,3149.10
33,P034,Webcam C920,Accessories,Logitech,6999,4.6,14,12,839.88,6159.12
34,P035,HDMI Cable,Accessories,AmazonBasics,799,4.4,50,25,199.75,599.25
35,P036,Power Bank 20000,Accessories,Ambrane,1999,4.3,35,18,359.82,1639.18
36,P037,Bluetooth Mouse,Accessories,HP,999,4.1,45,20,199.80,799.20
37,P038,Laptop Sleeve,Accessories,Targus,1799,4.2,28,15,269.85,1529.15
38,P039,Wireless Charger,Accessories,Belkin,2999,4.4,16,10,299.90,2699.10
39,P040,Cooling Pad,Accessories,Cooler Master,2499,4.3,20,12,299.88,2199.12
40,P041,MacBook Pro M3,Laptop,Apple,169000,4.9,5,4,6760.00,162240.00
41,P042,ThinkPad E14,Laptop,Lenovo,68000,4.4,11,10,6800.00,61200.00
42,P043,ROG Strix G16,Laptop,Asus,125000,4.7,6,8,10000.00,115000.00
43,P044,XPS 13,Laptop,Dell,115000,4.6,7,7,8050.00,106950.00
44,P045,Envy x360,Laptop,HP,82000,4.5,10,12,9840.00,72160.00
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4,5160.00,123840.00
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6,7800.00,122200.00
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15,3749.85,21249.15
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12,3599.88,26399.12
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18,3419.82,15579.18

In [63]:
df.groupby("category")["price"].mean().round(2)

category
Accessories     2439.0
Headphones     20377.6
Keyboard        9197.4
Laptop         87100.0
Mobile         63899.7
Monitor        28600.0
Tablet         46579.4
Name: price, dtype: float64

In [65]:
df.groupby("brand")["rating"].mean().round(1)

brand
AmazonBasics     4.4
Ambrane          4.3
Anker            4.5
Apple            4.8
Asus             4.5
Belkin           4.4
Bose             4.6
Cooler Master    4.3
Dell             4.4
Gigabyte         4.5
Google           4.4
HP               4.3
HyperX           4.5
JBL              4.3
Keychron         4.5
LG               4.5
Lenovo           4.3
Logitech         4.5
Motorola         4.4
Nothing          4.3
OnePlus          4.4
Portronics       4.2
Razer            4.6
Samsung          4.6
Sennheiser       4.5
Sony             4.8
Targus           4.2
Xiaomi           4.4
Name: rating, dtype: float64

In [67]:
df.loc[df.groupby("category")["price"].idxmax(),["category" ,"brand" , "price"]]

       category     brand   price
33  Accessories  Logitech    6999
10   Headphones      Sony   29990
18     Keyboard     Razer   10999
40       Laptop     Apple  169000
46       Mobile   Samsung  130000
22      Monitor      Asus   35000
26       Tablet   Samsung   72000

In [73]:
df.to_csv("final_products_data.csv", index=False)

In [74]:
pd.read_csv("final_products_data.csv")

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount,finl_price
0,P001,Inspiron 15,Laptop,Dell,55000,4.2,15,10,5500.00,49500.00
1,P002,IdeaPad Slim 3,Laptop,Lenovo,48000,4.1,20,12,5760.00,42240.00
2,P003,Pavilion 14,Laptop,HP,62000,4.3,12,8,4960.00,57040.00
3,P004,MacBook Air M2,Laptop,Apple,95000,4.7,8,5,4750.00,90250.00
4,P005,VivoBook 15,Laptop,Asus,52000,4.2,18,15,7800.00,44200.00
5,P006,Galaxy S24,Mobile,Samsung,72000,4.6,10,7,5040.00,66960.00
6,P007,iPhone 15,Mobile,Apple,70000,4.7,14,6,4200.00,65800.00
7,P008,OnePlus 12,Mobile,OnePlus,64000,4.5,16,10,6400.00,57600.00
8,P009,Pixel 8,Mobile,Google,58000,4.4,9,9,5220.00,52780.00
9,P010,Nothing Phone 2,Mobile,Nothing,42000,4.3,22,13,5460.00,36540.00
10,P011,WH-1000XM5,Headphones,Sony,29990,4.8,11,10,2999.00,26991.00
11,P012,AirPods Pro 2,Headphones,Apple,24900,4.7,18,5,1245.00,23655.00
12,P013,QuietComfort 45,Headphones,Bose,28000,4.6,7,12,3360.00,24640.00
13,P014,JBL Tune 760NC,Headphones,JBL,5999,4.3,25,20,1199.80,4799.20
14,P015,Sennheiser HD 450,Headphones,Sennheiser,12999,4.5,13,15,1949.85,11049.15
15,P016,MX Keys,Keyboard,Logitech,8999,4.6,20,10,899.90,8099.10
16,P017,K2 Mechanical,Keyboard,Keychron,9500,4.5,9,8,760.00,8740.00
17,P018,MK850,Keyboard,Logitech,7499,4.4,15,12,899.88,6599.12
18,P019,BlackWidow V3,Keyboard,Razer,10999,4.6,10,15,1649.85,9349.15
19,P020,Alloy Origins,Keyboard,HyperX,8990,4.5,17,10,899.00,8091.00
20,P021,UltraGear 27,Monitor,LG,28000,4.5,8,12,3360.00,24640.00
21,P022,Odyssey G5,Monitor,Samsung,32000,4.6,6,10,3200.00,28800.00
22,P023,VG27AQ,Monitor,Asus,35000,4.7,9,8,2800.00,32200.00
23,P024,S2721D,Monitor,Dell,22000,4.4,14,15,3300.00,18700.00
24,P025,M27Q,Monitor,Gigabyte,26000,4.5,12,10,2600.00,23400.00
25,P026,iPad Air,Tablet,Apple,59900,4.7,10,5,2995.00,56905.00
26,P027,Galaxy Tab S9,Tablet,Samsung,72000,4.6,7,10,7200.00,64800.00
27,P028,Pad 6,Tablet,Xiaomi,29999,4.5,18,12,3599.88,26399.12
28,P029,Tab P12,Tablet,Lenovo,32999,4.4,13,15,4949.85,28049.15
29,P030,OnePlus Pad,Tablet,OnePlus,37999,4.5,11,8,3039.92,34959.08
30,P031,Wireless Mouse,Accessories,Logitech,1299,4.3,40,20,259.80,1039.20
31,P032,Laptop Stand,Accessories,Portronics,1499,4.2,30,15,224.85,1274.15
32,P033,USB-C Hub,Accessories,Anker,3499,4.5,25,10,349.90,3149.10
33,P034,Webcam C920,Accessories,Logitech,6999,4.6,14,12,839.88,6159.12
34,P035,HDMI Cable,Accessories,AmazonBasics,799,4.4,50,25,199.75,599.25
35,P036,Power Bank 20000,Accessories,Ambrane,1999,4.3,35,18,359.82,1639.18
36,P037,Bluetooth Mouse,Accessories,HP,999,4.1,45,20,199.80,799.20
37,P038,Laptop Sleeve,Accessories,Targus,1799,4.2,28,15,269.85,1529.15
38,P039,Wireless Charger,Accessories,Belkin,2999,4.4,16,10,299.90,2699.10
39,P040,Cooling Pad,Accessories,Cooler Master,2499,4.3,20,12,299.88,2199.12
40,P041,MacBook Pro M3,Laptop,Apple,169000,4.9,5,4,6760.00,162240.00
41,P042,ThinkPad E14,Laptop,Lenovo,68000,4.4,11,10,6800.00,61200.00
42,P043,ROG Strix G16,Laptop,Asus,125000,4.7,6,8,10000.00,115000.00
43,P044,XPS 13,Laptop,Dell,115000,4.6,7,7,8050.00,106950.00
44,P045,Envy x360,Laptop,HP,82000,4.5,10,12,9840.00,72160.00
45,P046,iPhone 15 Pro,Mobile,Apple,129000,4.8,6,4,5160.00,123840.00
46,P047,Galaxy S24 Ultra,Mobile,Samsung,130000,4.8,5,6,7800.00,122200.00
47,P048,Nord CE 4,Mobile,OnePlus,24999,4.3,25,15,3749.85,21249.15
48,P049,Moto Edge 50,Mobile,Motorola,29999,4.4,19,12,3599.88,26399.12
49,P050,Redmi Note 13,Mobile,Xiaomi,18999,4.2,30,18,3419.82,15579.18