In [2]:
data="""customer_id,name,age,city,email,purchase_amount,rating
C001,  Teju ,33,hyderabad,TEJU@GMAIL.COM,2500,5
C002,RAHUL,28, HYDERABAD ,rahul@gmail.com,1500,4
C003,Priya,abc,Bangalore,priya@gmail.com,2000,5
C004, anil,35,HYDERABAD,anil@gmail.com,abc,4
C005,SITA,29,,sita@gmail.com,1800,3
C006,  Ravi,31,Chennai,ravi@gmail.com,2200,5
C007,MEENA,27, chennai ,MEENA@GMAIL.COM,1700,4
C008,Arjun,,Mumbai,arjun@gmail.com,3000,5
C009,  Kiran ,26,MUMBAI,kiran@gmail.com,1200,3
C010,swathi,30,Hyderabad,,2500,4
C011,  Vamsi,32,HYDERABAD,vamsi@gmail.com,2800,5
C012,PRIYA,29,bangalore,priya2@gmail.com,1900,4
C013,Rohit,34, Bangalore ,rohit@gmail.com,three thousand,5
C014,neha,25,Delhi,neha@gmail.com,1600,3
C015,  Suresh ,38,delhi,suresh@gmail.com,3500,5
C016,ANJALI,27, DELHI ,anjali@gmail.com,1400,4
C017,Manoj,40,Hyderabad,manoj@gmail.com,4200,5
C018,divya,,hyderabad,divya@gmail.com,2100,4
C019, Karthik ,33,Chennai,karthik@gmail.com,2300,5
C020,LATHA,31, chennai ,latha@gmail.com,1800,3
C021,Arun,29,Mumbai,arun@gmail.com,2700,4
C022,  Pooja ,26,mumbai,pooja@gmail.com,1500,5
C023,SHIVA,36,Bangalore,shiva@gmail.com,3200,4
C024,rekha,28, bangalore ,rekha@gmail.com,2000,3
C025,  Naveen,30,Hyderabad,naveen@gmail.com,2600,5
C026,PRIYANKA,abc,HYDERABAD,priyanka@gmail.com,1900,4
C027,Ramesh,42,hyderabad,ramesh@gmail.com,5000,5
C028,  Kavya ,24,Delhi,kavya@gmail.com,1300,3
C029,SANDEEP,35, delhi ,sandeep@gmail.com,3100,4
C030,lakshmi,32,Chennai,lakshmi@gmail.com,2200,5
C031,  Harish ,29,chennai,harish@gmail.com,2400,4
C032,POOJA,27, MUMBAI ,pooja2@gmail.com,1700,3
C033,Vijay,39,Mumbai,vijay@gmail.com,3900,5
C034,  Sneha ,28,Hyderabad,sneha@gmail.com,2000,4
C035,RAJ,31,hyderabad,raj@gmail.com,2800,5
C036,keerthi,25,Bangalore,keerthi@gmail.com,1500,3
C037,  Ajay,34, Bangalore ,ajay@gmail.com,2700,4
C038,SWATHI,30,Delhi,swathi@gmail.com,2200,5
C039,Prakash,,delhi,prakash@gmail.com,3300,4
C040,  Nisha ,27,Chennai,nisha@gmail.com,1800,3
C041,MOHAN,41, chennai ,mohan@gmail.com,4500,5
C042,Deepa,29,Mumbai,deepa@gmail.com,2100,4
C043,  Sanjana,26,mumbai,sanjana@gmail.com,1600,3
C044,ABHISHEK,37,Hyderabad,abhishek@gmail.com,3700,5
C045,roopa,33, HYDERABAD ,roopa@gmail.com,2500,4
C046,  Tarun ,28,Bangalore,tarun@gmail.com,1900,3
C047,MANASA,30,bangalore,manasa@gmail.com,2300,5
C048,Krishna,36,Delhi,krishna@gmail.com,3400,4
C049,  Asha ,27, delhi ,asha@gmail.com,1400,3
C050,Rajesh,43,Chennai,rajesh@gmail.com,4800,5
C051,  Teju ,33,hyderabad,TEJU@GMAIL.COM,2500,5
C052,rahul,28, HYDERABAD ,rahul@gmail.com,1500,4
C053,Priya,29,Bangalore,priya3@gmail.com,2000,5
C054,anil,35,HYDERABAD,anil2@gmail.com,3200,4
C055,SITA,,Mumbai,sita2@gmail.com,1800,3
C056,Ravi,31,Chennai,ravi2@gmail.com,2200,5
C057, meena ,27, chennai ,meena2@gmail.com,1700,4
C058,Arjun,26,Mumbai,arjun2@gmail.com,3000,5
C059,Kiran,26,MUMBAI,kiran2@gmail.com,1200,3
C060,SWATHI,30,Hyderabad,swathi2@gmail.com,2500,4
C061,Vamsi,32,HYDERABAD,vamsi2@gmail.com,2800,5
C062,priya,29,bangalore,priya4@gmail.com,1900,4
C063,Rohit,34, Bangalore ,rohit2@gmail.com,3000,5
C064,Neha,25,Delhi,neha2@gmail.com,1600,3
C065,Suresh,38,delhi,suresh2@gmail.com,3500,5
C066,anjali,27, DELHI ,anjali2@gmail.com,1400,4
C067,Manoj,40,Hyderabad,manoj2@gmail.com,4200,5
C068,divya,28,hyderabad,divya2@gmail.com,2100,4
C069,Karthik,33,Chennai,karthik2@gmail.com,2300,5
C070,latha,31, chennai ,latha2@gmail.com,1800,3
C071,Arun,29,Mumbai,arun2@gmail.com,2700,4
C072,Pooja,26,mumbai,pooja3@gmail.com,1500,5
C073,SHIVA,36,Bangalore,shiva2@gmail.com,3200,4
C074,rekha,28, bangalore ,rekha2@gmail.com,2000,3
C075,Naveen,30,Hyderabad,naveen2@gmail.com,2600,5
C076,Priyanka,27,HYDERABAD,priyanka2@gmail.com,1900,4
C077,Ramesh,42,hyderabad,ramesh2@gmail.com,5000,5
C078,Kavya,24,Delhi,kavya2@gmail.com,1300,3
C079,Sandeep,35, delhi ,sandeep2@gmail.com,3100,4
C080,Lakshmi,32,Chennai,lakshmi2@gmail.com,2200,5
C081,Harish,29,chennai,harish2@gmail.com,2400,4
C082,POOJA,27, MUMBAI ,pooja4@gmail.com,1700,3
C083,Vijay,39,Mumbai,vijay2@gmail.com,3900,5
C084,Sneha,28,Hyderabad,sneha2@gmail.com,2000,4
C085,Raj,31,hyderabad,raj2@gmail.com,2800,5
C086,keerthi,25,Bangalore,keerthi2@gmail.com,1500,3
C087,Ajay,34, Bangalore ,ajay2@gmail.com,2700,4
C088,SWATHI,30,Delhi,swathi3@gmail.com,2200,5
C089,Prakash,38,delhi,prakash2@gmail.com,3300,4
C090,Nisha,27,Chennai,nisha2@gmail.com,1800,3
C091,Mohan,41, chennai ,mohan2@gmail.com,4500,5
C092,Deepa,29,Mumbai,deepa2@gmail.com,2100,4
C093,Sanjana,26,mumbai,sanjana2@gmail.com,1600,3
C094,ABHISHEK,37,Hyderabad,abhishek2@gmail.com,3700,5
C095,roopa,33, HYDERABAD ,roopa2@gmail.com,2500,4
C096,Tarun,28,Bangalore,tarun2@gmail.com,1900,3
C097,MANASA,30,bangalore,manasa2@gmail.com,2300,5
C098,Krishna,36,Delhi,krishna2@gmail.com,3400,4
C099,Asha,27, delhi ,asha2@gmail.com,1400,3
C100,Rajesh,43,Chennai,rajesh2@gmail.com,4800,5
C101,  Teju ,33,hyderabad,TEJU@GMAIL.COM,2500,5
C102,rahul,28, HYDERABAD ,rahul3@gmail.com,1500,4
C103,,31,Chennai,emptyname@gmail.com,2200,4
C104,  Anu ,29,,anu@gmail.com,,5
C105,Ravi,thirty,Mumbai,ravi3@gmail.com,abc,good"""

In [3]:
with open("data.txt" , "w") as file:
    file.write(data)

In [4]:
import pandas as pd
df=pd.read_csv("data.txt")

In [5]:
df

,customer_id,name,age,city,email,purchase_amount,rating
0,C001,Teju,33,hyderabad,TEJU@GMAIL.COM,2500,5
1,C002,RAHUL,28,HYDERABAD,rahul@gmail.com,1500,4
2,C003,Priya,abc,Bangalore,priya@gmail.com,2000,5
3,C004,anil,35,HYDERABAD,anil@gmail.com,abc,4
4,C005,SITA,29,NaN,sita@gmail.com,1800,3
...,...,...,...,...,...,...,...
100,C101,Teju,33,hyderabad,TEJU@GMAIL.COM,2500,5
101,C102,rahul,28,HYDERABAD,rahul3@gmail.com,1500,4
102,C103,NaN,31,Chennai,emptyname@gmail.com,2200,4
103,C104,Anu,29,NaN,anu@gmail.com,NaN,5
104,C105,Ravi,thirty,Mumbai,ravi3@gmail.com,abc,good

In [7]:
print("Messy Dataframe: ", df.shape)

Messy Dataframe:  (105, 7)

In [8]:
df.isnull()

     customer_id   name    age   city  email  purchase_amount  rating
0          False  False  False  False  False            False   False
1          False  False  False  False  False            False   False
2          False  False  False  False  False            False   False
3          False  False  False  False  False            False   False
4          False  False  False   True  False            False   False
..           ...    ...    ...    ...    ...              ...     ...
100        False  False  False  False  False            False   False
101        False  False  False  False  False            False   False
102        False   True  False  False  False            False   False
103        False  False  False   True  False             True   False
104        False  False  False  False  False            False   False

[105 rows x 7 columns]

In [9]:
df.isnull().sum()

customer_id        0
name               1
age                4
city               2
email              1
purchase_amount    1
rating             0
dtype: int64

In [10]:
df.dropna()

,customer_id,name,age,city,email,purchase_amount,rating
0,C001,Teju,33,hyderabad,TEJU@GMAIL.COM,2500,5
1,C002,RAHUL,28,HYDERABAD,rahul@gmail.com,1500,4
2,C003,Priya,abc,Bangalore,priya@gmail.com,2000,5
3,C004,anil,35,HYDERABAD,anil@gmail.com,abc,4
5,C006,Ravi,31,Chennai,ravi@gmail.com,2200,5
...,...,...,...,...,...,...,...
98,C099,Asha,27,delhi,asha2@gmail.com,1400,3
99,C100,Rajesh,43,Chennai,rajesh2@gmail.com,4800,5
100,C101,Teju,33,hyderabad,TEJU@GMAIL.COM,2500,5
101,C102,rahul,28,HYDERABAD,rahul3@gmail.com,1500,4
104,C105,Ravi,thirty,Mumbai,ravi3@gmail.com,abc,good

In [13]:
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["purchase_amount"]=pd.to_numeric(df["purchase_amount"],errors="coerce")
df["rating"]=pd.to_numeric(df["rating"],errors="coerce")

df["customer_id"]=df["customer_id"].fillna("Unknown")
df["name"]=df["name"].fillna("Unknown")
df["city"]=df["city"].fillna("Unknown")
df["email"]=df["email"].fillna("Unknown")
df["age"]=df["age"].fillna(df["age"].mean().round(1))
df["purchase_amount"]=df["purchase_amount"].fillna(df["age"].mean().round(1))
df["rating"]=df["rating"].fillna(df["age"].mean().round(1))

In [14]:
df

,customer_id,name,age,city,email,purchase_amount,rating
0,C001,Teju,33.00000,hyderabad,TEJU@GMAIL.COM,2500.00000,5.00000
1,C002,RAHUL,28.00000,HYDERABAD,rahul@gmail.com,1500.00000,4.00000
2,C003,Priya,31.22449,Bangalore,priya@gmail.com,2000.00000,5.00000
3,C004,anil,35.00000,HYDERABAD,anil@gmail.com,31.22449,4.00000
4,C005,SITA,29.00000,Unknown,sita@gmail.com,1800.00000,3.00000
...,...,...,...,...,...,...,...
100,C101,Teju,33.00000,hyderabad,TEJU@GMAIL.COM,2500.00000,5.00000
101,C102,rahul,28.00000,HYDERABAD,rahul3@gmail.com,1500.00000,4.00000
102,C103,Unknown,31.00000,Chennai,emptyname@gmail.com,2200.00000,4.00000
103,C104,Anu,29.00000,Unknown,anu@gmail.com,31.22449,5.00000
104,C105,Ravi,31.22449,Mumbai,ravi3@gmail.com,31.22449,31.22449

In [16]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
100    False
101    False
102    False
103    False
104    False
Length: 105, dtype: bool

In [17]:
df=df.drop_duplicates()

In [18]:
df

,customer_id,name,age,city,email,purchase_amount,rating
0,C001,Teju,33.00000,hyderabad,TEJU@GMAIL.COM,2500.00000,5.00000
1,C002,RAHUL,28.00000,HYDERABAD,rahul@gmail.com,1500.00000,4.00000
2,C003,Priya,31.22449,Bangalore,priya@gmail.com,2000.00000,5.00000
3,C004,anil,35.00000,HYDERABAD,anil@gmail.com,31.22449,4.00000
4,C005,SITA,29.00000,Unknown,sita@gmail.com,1800.00000,3.00000
...,...,...,...,...,...,...,...
100,C101,Teju,33.00000,hyderabad,TEJU@GMAIL.COM,2500.00000,5.00000
101,C102,rahul,28.00000,HYDERABAD,rahul3@gmail.com,1500.00000,4.00000
102,C103,Unknown,31.00000,Chennai,emptyname@gmail.com,2200.00000,4.00000
103,C104,Anu,29.00000,Unknown,anu@gmail.com,31.22449,5.00000
104,C105,Ravi,31.22449,Mumbai,ravi3@gmail.com,31.22449,31.22449

In [19]:
df["age"]=df["age"].astype(int)
df["purchase_amount"]=df["purchase_amount"].astype(int)
df["rating"]=df["rating"].astype(int)

In [20]:
df["name"]=df["name"].str.strip()
df["city"]=df["name"].str.title()

In [ ]:
df["email"]=df["name"].str.strip().str.lower()
df["customer_id	"]=df["customer_id	"].str.upper()