In [1]:
students = [
    {"student_id": "S001", "name": "Ravi", "age": 21, "city": "Hyderabad", "python_marks": 85, "sql_marks": 78, "pandas_marks": 82, "attendance": 92},
    {"student_id": "S002", "name": "Anu", "age": 22, "city": "Chennai", "python_marks": 90, "sql_marks": 88, "pandas_marks": 91, "attendance": 95},
    {"student_id": "S003", "name": "Kiran", "age": 20, "city": "Bangalore", "python_marks": 76, "sql_marks": 81, "pandas_marks": 79, "attendance": 89},
    {"student_id": "S004", "name": "Priya", "age": 21, "city": "Mumbai", "python_marks": 88, "sql_marks": 84, "pandas_marks": 86, "attendance": 94},
    {"student_id": "S005", "name": "Arjun", "age": 23, "city": "Pune", "python_marks": 72, "sql_marks": 75, "pandas_marks": 70, "attendance": 85},
    {"student_id": "S006", "name": "Sneha", "age": 20, "city": "Delhi", "python_marks": 95, "sql_marks": 91, "pandas_marks": 93, "attendance": 97},
    {"student_id": "S007", "name": "Vijay", "age": 22, "city": "Hyderabad", "python_marks": 68, "sql_marks": 74, "pandas_marks": 71, "attendance": 82},
    {"student_id": "S008", "name": "Meena", "age": 21, "city": "Kolkata", "python_marks": 84, "sql_marks": 80, "pandas_marks": 85, "attendance": 91},
    {"student_id": "S009", "name": "Rahul", "age": 24, "city": "Bangalore", "python_marks": 79, "sql_marks": 83, "pandas_marks": 77, "attendance": 88},
    {"student_id": "S010", "name": "Divya", "age": 22, "city": "Chennai", "python_marks": 92, "sql_marks": 89, "pandas_marks": 94, "attendance": 96},
    {"student_id": "S011", "name": "Suresh", "age": 23, "city": "Mumbai", "python_marks": 65, "sql_marks": 70, "pandas_marks": 68, "attendance": 80},
    {"student_id": "S012", "name": "Pooja", "age": 20, "city": "Pune", "python_marks": 87, "sql_marks": 85, "pandas_marks": 89, "attendance": 93},
    {"student_id": "S013", "name": "Amit", "age": 21, "city": "Delhi", "python_marks": 74, "sql_marks": 79, "pandas_marks": 76, "attendance": 86},
    {"student_id": "S014", "name": "Lakshmi", "age": 22, "city": "Hyderabad", "python_marks": 91, "sql_marks": 93, "pandas_marks": 90, "attendance": 98},
    {"student_id": "S015", "name": "Nikhil", "age": 23, "city": "Kolkata", "python_marks": 81, "sql_marks": 77, "pandas_marks": 80, "attendance": 90},
    {"student_id": "S016", "name": "Swathi", "age": 21, "city": "Bangalore", "python_marks": 89, "sql_marks": 86, "pandas_marks": 88, "attendance": 94},
    {"student_id": "S017", "name": "Manoj", "age": 24, "city": "Chennai", "python_marks": 70, "sql_marks": 73, "pandas_marks": 75, "attendance": 84},
    {"student_id": "S018", "name": "Harika", "age": 20, "city": "Hyderabad", "python_marks": 94, "sql_marks": 90, "pandas_marks": 92, "attendance": 97},
    {"student_id": "S019", "name": "Rohit", "age": 22, "city": "Mumbai", "python_marks": 78, "sql_marks": 82, "pandas_marks": 79, "attendance": 87},
    {"student_id": "S020", "name": "Neha", "age": 21, "city": "Pune", "python_marks": 86, "sql_marks": 88, "pandas_marks": 84, "attendance": 92},
    {"student_id": "S021", "name": "Varun", "age": 23, "city": "Delhi", "python_marks": 73, "sql_marks": 69, "pandas_marks": 72, "attendance": 81},
    {"student_id": "S022", "name": "Kavya", "age": 20, "city": "Kolkata", "python_marks": 90, "sql_marks": 92, "pandas_marks": 91, "attendance": 96},
    {"student_id": "S023", "name": "Ajay", "age": 22, "city": "Bangalore", "python_marks": 82, "sql_marks": 79, "pandas_marks": 83, "attendance": 89},
    {"student_id": "S024", "name": "Deepika", "age": 21, "city": "Chennai", "python_marks": 96, "sql_marks": 94, "pandas_marks": 95, "attendance": 99},
    {"student_id": "S025", "name": "Mohan", "age": 23, "city": "Hyderabad", "python_marks": 77, "sql_marks": 80, "pandas_marks": 78, "attendance": 86}
]

In [5]:
import csv
with open("students_results.csv" , "w") as file:
    writer=csv.DictWriter(file,fieldnames=students[0].keys())
    writer.writeheader()
    writer.writerows(students)
print("CSV file created successfully")

CSV file created successfully

In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Eswar\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Eswar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Eswar\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
df=pd.read_csv("students_results.csv")

In [8]:
df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,S001,Ravi,21,Hyderabad,85,78,82,92
1,S002,Anu,22,Chennai,90,88,91,95
2,S003,Kiran,20,Bangalore,76,81,79,89
3,S004,Priya,21,Mumbai,88,84,86,94
4,S005,Arjun,23,Pune,72,75,70,85

In [9]:
df.tail()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
20,S021,Varun,23,Delhi,73,69,72,81
21,S022,Kavya,20,Kolkata,90,92,91,96
22,S023,Ajay,22,Bangalore,82,79,83,89
23,S024,Deepika,21,Chennai,96,94,95,99
24,S025,Mohan,23,Hyderabad,77,80,78,86

In [10]:
df.shape

(25, 8)

In [11]:
df.columns

Index(['student_id', 'name', 'age', 'city', 'python_marks', 'sql_marks',
       'pandas_marks', 'attendance'],
      dtype='str')

In [12]:
df.dtypes

student_id        str
name              str
age             int64
city              str
python_marks    int64
sql_marks       int64
pandas_marks    int64
attendance      int64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    25 non-null     str
 1   name          25 non-null     str
 2   age           25 non-null     int64
 3   city          25 non-null     str
 4   python_marks  25 non-null     int64
 5   sql_marks     25 non-null     int64
 6   pandas_marks  25 non-null     int64
 7   attendance    25 non-null     int64
dtypes: int64(5), str(3)
memory usage: 1.7 KB

In [14]:
df.describe()

          age  python_marks  sql_marks  pandas_marks  attendance
count  25.000     25.000000  25.000000     25.000000   25.000000
mean   21.680     82.480000  82.400000     82.720000   90.440000
std     1.249      8.926179   7.164728      8.090735    5.545869
min    20.000     65.000000  69.000000     68.000000   80.000000
25%    21.000     76.000000  78.000000     77.000000   86.000000
50%    22.000     84.000000  82.000000     83.000000   91.000000
75%    23.000     90.000000  88.000000     90.000000   95.000000
max    24.000     96.000000  94.000000     95.000000   99.000000

In [17]:
df[["python_marks","sql_marks" , "pandas_marks"]].mean()

python_marks    82.48
sql_marks       82.40
pandas_marks    82.72
dtype: float64

In [18]:
df[["python_marks","sql_marks" , "pandas_marks"]].max().max()

np.int64(96)

In [19]:
df[["python_marks","sql_marks" , "pandas_marks"]].min().min()

np.int64(65)

In [20]:
df.sort_values("python_marks")["name"]

10     Suresh
6       Vijay
16      Manoj
4       Arjun
20      Varun
12       Amit
2       Kiran
24      Mohan
18      Rohit
8       Rahul
14     Nikhil
22       Ajay
7       Meena
0        Ravi
19       Neha
11      Pooja
3       Priya
15     Swathi
21      Kavya
1         Anu
13    Lakshmi
9       Divya
17     Harika
5       Sneha
23    Deepika
Name: name, dtype: str

In [21]:
df.sort_values("attendance")["name"]

10     Suresh
20      Varun
6       Vijay
16      Manoj
4       Arjun
24      Mohan
12       Amit
18      Rohit
8       Rahul
2       Kiran
22       Ajay
14     Nikhil
7       Meena
0        Ravi
19       Neha
11      Pooja
15     Swathi
3       Priya
1         Anu
9       Divya
21      Kavya
5       Sneha
17     Harika
13    Lakshmi
23    Deepika
Name: name, dtype: str

In [23]:
df[df["python_marks"]>80]["name"]

0        Ravi
1         Anu
3       Priya
5       Sneha
7       Meena
9       Divya
11      Pooja
13    Lakshmi
14     Nikhil
15     Swathi
17     Harika
19       Neha
21      Kavya
22       Ajay
23    Deepika
Name: name, dtype: str

In [24]:
df[df["attendance"]>75]["name"]

0        Ravi
1         Anu
2       Kiran
3       Priya
4       Arjun
5       Sneha
6       Vijay
7       Meena
8       Rahul
9       Divya
10     Suresh
11      Pooja
12       Amit
13    Lakshmi
14     Nikhil
15     Swathi
16      Manoj
17     Harika
18      Rohit
19       Neha
20      Varun
21      Kavya
22       Ajay
23    Deepika
24      Mohan
Name: name, dtype: str

In [25]:
df[["name" ,"python_marks" , "pandas_marks"]]

       name  python_marks  pandas_marks
0      Ravi            85            82
1       Anu            90            91
2     Kiran            76            79
3     Priya            88            86
4     Arjun            72            70
5     Sneha            95            93
6     Vijay            68            71
7     Meena            84            85
8     Rahul            79            77
9     Divya            92            94
10   Suresh            65            68
11    Pooja            87            89
12     Amit            74            76
13  Lakshmi            91            90
14   Nikhil            81            80
15   Swathi            89            88
16    Manoj            70            75
17   Harika            94            92
18    Rohit            78            79
19     Neha            86            84
20    Varun            73            72
21    Kavya            90            91
22     Ajay            82            83
23  Deepika            96            95
24    Mohan            77            78

In [27]:
df["total_marks"]=df[["python_marks" , "sql_marks" ,"pandas_marks"]].sum(axis=1)

In [28]:
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks
0,S001,Ravi,21,Hyderabad,85,78,82,92,245
1,S002,Anu,22,Chennai,90,88,91,95,269
2,S003,Kiran,20,Bangalore,76,81,79,89,236
3,S004,Priya,21,Mumbai,88,84,86,94,258
4,S005,Arjun,23,Pune,72,75,70,85,217
5,S006,Sneha,20,Delhi,95,91,93,97,279
6,S007,Vijay,22,Hyderabad,68,74,71,82,213
7,S008,Meena,21,Kolkata,84,80,85,91,249
8,S009,Rahul,24,Bangalore,79,83,77,88,239
9,S010,Divya,22,Chennai,92,89,94,96,275
10,S011,Suresh,23,Mumbai,65,70,68,80,203
11,S012,Pooja,20,Pune,87,85,89,93,261
12,S013,Amit,21,Delhi,74,79,76,86,229
13,S014,Lakshmi,22,Hyderabad,91,93,90,98,274
14,S015,Nikhil,23,Kolkata,81,77,80,90,238
15,S016,Swathi,21,Bangalore,89,86,88,94,263
16,S017,Manoj,24,Chennai,70,73,75,84,218
17,S018,Harika,20,Hyderabad,94,90,92,97,276
18,S019,Rohit,22,Mumbai,78,82,79,87,239
19,S020,Neha,21,Pune,86,88,84,92,258
20,S021,Varun,23,Delhi,73,69,72,81,214
21,S022,Kavya,20,Kolkata,90,92,91,96,273
22,S023,Ajay,22,Bangalore,82,79,83,89,244
23,S024,Deepika,21,Chennai,96,94,95,99,285
24,S025,Mohan,23,Hyderabad,77,80,78,86,235

In [31]:
df["average_marks"]=df[["python_marks" , "sql_marks" ,"pandas_marks"]].mean(axis=1).round(2)

In [32]:
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
0,S001,Ravi,21,Hyderabad,85,78,82,92,245,81.67
1,S002,Anu,22,Chennai,90,88,91,95,269,89.67
2,S003,Kiran,20,Bangalore,76,81,79,89,236,78.67
3,S004,Priya,21,Mumbai,88,84,86,94,258,86.00
4,S005,Arjun,23,Pune,72,75,70,85,217,72.33
5,S006,Sneha,20,Delhi,95,91,93,97,279,93.00
6,S007,Vijay,22,Hyderabad,68,74,71,82,213,71.00
7,S008,Meena,21,Kolkata,84,80,85,91,249,83.00
8,S009,Rahul,24,Bangalore,79,83,77,88,239,79.67
9,S010,Divya,22,Chennai,92,89,94,96,275,91.67
10,S011,Suresh,23,Mumbai,65,70,68,80,203,67.67
11,S012,Pooja,20,Pune,87,85,89,93,261,87.00
12,S013,Amit,21,Delhi,74,79,76,86,229,76.33
13,S014,Lakshmi,22,Hyderabad,91,93,90,98,274,91.33
14,S015,Nikhil,23,Kolkata,81,77,80,90,238,79.33
15,S016,Swathi,21,Bangalore,89,86,88,94,263,87.67
16,S017,Manoj,24,Chennai,70,73,75,84,218,72.67
17,S018,Harika,20,Hyderabad,94,90,92,97,276,92.00
18,S019,Rohit,22,Mumbai,78,82,79,87,239,79.67
19,S020,Neha,21,Pune,86,88,84,92,258,86.00
20,S021,Varun,23,Delhi,73,69,72,81,214,71.33
21,S022,Kavya,20,Kolkata,90,92,91,96,273,91.00
22,S023,Ajay,22,Bangalore,82,79,83,89,244,81.33
23,S024,Deepika,21,Chennai,96,94,95,99,285,95.00
24,S025,Mohan,23,Hyderabad,77,80,78,86,235,78.33

In [33]:
import os
os.makedirs("output" , exist_ok=True)
df.to_csv("output/student_results.csv" , index=False)