In [2]:
data="""ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
TCK-1001,Aarav Sharma,Payment,Medium,Resolved,Alice Smith,4.5 hours
TCK-1002,Priya Patel,Technical,High,In Progress,Bob Jones,N/A
TCK-1003,Rohan Gupta,Login,Low,Resolved,Charlie Brown,1.2 hours
TCK-1004,Ananya Iyer,Course,Medium,Open,Unassigned,N/A
TCK-1005,Vikram Singh,Refund,Critical,Resolved,Diana Prince,24.0 hours
TCK-1006,Neha Verma,Account,Low,Closed,Alice Smith,2.0 hours
TCK-1007,Amit Kumar,Payment,High,In Progress,Bob Jones,N/A
TCK-1008,Sneha Reddy,Technical,Critical,Open,Unassigned,N/A
TCK-1009,Rahul Nair,Login,Medium,Resolved,Charlie Brown,0.5 hours
TCK-1010,Kavita Joshi,Course,Low,Closed,Diana Prince,12.5 hours
TCK-1011,Manish Rao,Refund,Medium,In Progress,Alice Smith,N/A
TCK-1012,Pooja Menon,Account,High,Resolved,Bob Jones,6.0 hours
TCK-1013,Suresh Pillai,Payment,Low,Open,Unassigned,N/A
TCK-1014,Divya Das,Technical,Medium,Resolved,Charlie Brown,3.1 hours
TCK-1015,Karan Malhotra,Login,Critical,Closed,Diana Prince,1.0 hours
TCK-1016,Meera Sen,Course,High,In Progress,Alice Smith,N/A
TCK-1017,Arjun Mehta,Refund,Low,Resolved,Bob Jones,18.2 hours
TCK-1018,Tanvi Kapoor,Account,Medium,Open,Unassigned,N/A
TCK-1019,Alok Banerjee,Payment,Critical,Resolved,Charlie Brown,5.0 hours
TCK-1020,Deepika Roy,Technical,Low,Closed,Diana Prince,4.0 hours
TCK-1021,Nikhil Joshi,Login,High,Resolved,Alice Smith,0.8 hours
TCK-1022,Swati Ghosh,Course,Medium,In Progress,Bob Jones,N/A
TCK-1023,Rajesh Kumar,Refund,High,Open,Unassigned,N/A
TCK-1024,Sunita Sharma,Account,Low,Resolved,Charlie Brown,2.5 hours
TCK-1025,Manoj Verma,Payment,Medium,Closed,Diana Prince,7.1 hours
TCK-1026,Geeta Iyer,Technical,Critical,In Progress,Alice Smith,N/A
TCK-1027,Abhishek Patel,Login,Low,Resolved,Bob Jones,0.3 hours
TCK-1028,Pallavi Rao,Course,High,Resolved,Charlie Brown,15.0 hours
TCK-1029,Sanjay Gupta,Refund,Medium,Open,Unassigned,N/A
TCK-1030,Ritu Singh,Account,Critical,Resolved,Diana Prince,9.4 hours
TCK-1031,Kunal Nair,Payment,Low,Closed,Alice Smith,3.8 hours
TCK-1032,Nisha Menon,Technical,Medium,In Progress,Bob Jones,N/A
TCK-1033,Varun Pillai,Login,High,Resolved,Charlie Brown,1.1 hours
TCK-1034,Payal Das,Course,Low,Open,Unassigned,N/A
TCK-1035,Tarun Malhotra,Refund,Critical,Resolved,Diana Prince,30.2 hours
TCK-1036,Shruti Sen,Account,Medium,Closed,Alice Smith,5.5 hours
TCK-1037,Vineet Mehta,Payment,High,In Progress,Bob Jones,N/A
TCK-1038,Pooja Kapoor,Technical,Critical,Open,Unassigned,N/A
TCK-1039,Ashish Banerjee,Login,Medium,Resolved,Charlie Brown,0.9 hours
TCK-1040,Kriti Roy,Course,Low,Closed,Diana Prince,11.0 hours
TCK-1041,Siddharth Joshi,Refund,Medium,In Progress,Alice Smith,N/A
TCK-1042,Neha Ghosh,Account,High,Resolved,Bob Jones,4.2 hours
TCK-1043,Rohit Kumar,Payment,Low,Open,Unassigned,N/A
TCK-1044,Ananya Sharma,Technical,Medium,Resolved,Charlie Brown,2.8 hours
TCK-1045,Vikram Patel,Login,Critical,Closed,Diana Prince,0.7 hours
TCK-1046,Priya Rao,Course,High,In Progress,Alice Smith,N/A
TCK-1047,Amit Gupta,Refund,Low,Resolved,Bob Jones,19.5 hours
TCK-1048,Sneha Singh,Account,Medium,Open,Unassigned,N/A
TCK-1049,Rahul Nair,Payment,Critical,Resolved,Charlie Brown,6.2 hours
TCK-1050,Kavita Menon,Technical,Low,Closed,Diana Prince,3.5 hours
"""

In [3]:
with open("tickets.csv", "w") as file:
    file.write(data)

In [4]:
import pandas as pd
df=pd.read_csv("tickets.csv")

In [5]:
df.shape[0]

50

In [ ]:
category_df=(df["category"].value_counts()).reset_index()
category_df.columns=["category" , "Tickets"]

In [ ]:
priority_df=(df["priority"].value_counts()).reset_index()
priority_df.columns=["priority" , "Tickets"]

In [ ]:
status_df=(df["status"].value_counts()).reset_index()
status_df.columns=["status" , "Tickets"]

In [9]:
df[df["status"]=="Open"]

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
3,TCK-1004,Ananya Iyer,Course,Medium,Open,Unassigned,NaN
7,TCK-1008,Sneha Reddy,Technical,Critical,Open,Unassigned,NaN
12,TCK-1013,Suresh Pillai,Payment,Low,Open,Unassigned,NaN
17,TCK-1018,Tanvi Kapoor,Account,Medium,Open,Unassigned,NaN
22,TCK-1023,Rajesh Kumar,Refund,High,Open,Unassigned,NaN
28,TCK-1029,Sanjay Gupta,Refund,Medium,Open,Unassigned,NaN
33,TCK-1034,Payal Das,Course,Low,Open,Unassigned,NaN
37,TCK-1038,Pooja Kapoor,Technical,Critical,Open,Unassigned,NaN
42,TCK-1043,Rohit Kumar,Payment,Low,Open,Unassigned,NaN
47,TCK-1048,Sneha Singh,Account,Medium,Open,Unassigned,NaN

In [10]:
df[df["status"]=="In Progress"]

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
1,TCK-1002,Priya Patel,Technical,High,In Progress,Bob Jones,NaN
6,TCK-1007,Amit Kumar,Payment,High,In Progress,Bob Jones,NaN
10,TCK-1011,Manish Rao,Refund,Medium,In Progress,Alice Smith,NaN
15,TCK-1016,Meera Sen,Course,High,In Progress,Alice Smith,NaN
21,TCK-1022,Swati Ghosh,Course,Medium,In Progress,Bob Jones,NaN
25,TCK-1026,Geeta Iyer,Technical,Critical,In Progress,Alice Smith,NaN
31,TCK-1032,Nisha Menon,Technical,Medium,In Progress,Bob Jones,NaN
36,TCK-1037,Vineet Mehta,Payment,High,In Progress,Bob Jones,NaN
40,TCK-1041,Siddharth Joshi,Refund,Medium,In Progress,Alice Smith,NaN
45,TCK-1046,Priya Rao,Course,High,In Progress,Alice Smith,NaN

In [11]:
df[df["status"]=="Resolved"]

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
0,TCK-1001,Aarav Sharma,Payment,Medium,Resolved,Alice Smith,4.5 hours
2,TCK-1003,Rohan Gupta,Login,Low,Resolved,Charlie Brown,1.2 hours
4,TCK-1005,Vikram Singh,Refund,Critical,Resolved,Diana Prince,24.0 hours
8,TCK-1009,Rahul Nair,Login,Medium,Resolved,Charlie Brown,0.5 hours
11,TCK-1012,Pooja Menon,Account,High,Resolved,Bob Jones,6.0 hours
13,TCK-1014,Divya Das,Technical,Medium,Resolved,Charlie Brown,3.1 hours
16,TCK-1017,Arjun Mehta,Refund,Low,Resolved,Bob Jones,18.2 hours
18,TCK-1019,Alok Banerjee,Payment,Critical,Resolved,Charlie Brown,5.0 hours
20,TCK-1021,Nikhil Joshi,Login,High,Resolved,Alice Smith,0.8 hours
23,TCK-1024,Sunita Sharma,Account,Low,Resolved,Charlie Brown,2.5 hours
26,TCK-1027,Abhishek Patel,Login,Low,Resolved,Bob Jones,0.3 hours
27,TCK-1028,Pallavi Rao,Course,High,Resolved,Charlie Brown,15.0 hours
29,TCK-1030,Ritu Singh,Account,Critical,Resolved,Diana Prince,9.4 hours
32,TCK-1033,Varun Pillai,Login,High,Resolved,Charlie Brown,1.1 hours
34,TCK-1035,Tarun Malhotra,Refund,Critical,Resolved,Diana Prince,30.2 hours
38,TCK-1039,Ashish Banerjee,Login,Medium,Resolved,Charlie Brown,0.9 hours
41,TCK-1042,Neha Ghosh,Account,High,Resolved,Bob Jones,4.2 hours
43,TCK-1044,Ananya Sharma,Technical,Medium,Resolved,Charlie Brown,2.8 hours
46,TCK-1047,Amit Gupta,Refund,Low,Resolved,Bob Jones,19.5 hours
48,TCK-1049,Rahul Nair,Payment,Critical,Resolved,Charlie Brown,6.2 hours

In [12]:

df["resolution_time"]=df["resolution_time"].str.strip().str.replace("hours","",regex=False)

In [13]:
df["resolution_time"].astype(float)

0      4.5
1      NaN
2      1.2
3      NaN
4     24.0
5      2.0
6      NaN
7      NaN
8      0.5
9     12.5
10     NaN
11     6.0
12     NaN
13     3.1
14     1.0
15     NaN
16    18.2
17     NaN
18     5.0
19     4.0
20     0.8
21     NaN
22     NaN
23     2.5
24     7.1
25     NaN
26     0.3
27    15.0
28     NaN
29     9.4
30     3.8
31     NaN
32     1.1
33     NaN
34    30.2
35     5.5
36     NaN
37     NaN
38     0.9
39    11.0
40     NaN
41     4.2
42     NaN
43     2.8
44     0.7
45     NaN
46    19.5
47     NaN
48     6.2
49     3.5
Name: resolution_time, dtype: float64

In [14]:
df["resolution_time"].fillna(0)

0      4.5
1         0
2      1.2
3         0
4     24.0
5      2.0
6         0
7         0
8      0.5
9     12.5
10        0
11     6.0
12        0
13     3.1
14     1.0
15        0
16    18.2
17        0
18     5.0
19     4.0
20     0.8
21        0
22        0
23     2.5
24     7.1
25        0
26     0.3
27    15.0
28        0
29     9.4
30     3.8
31        0
32     1.1
33        0
34    30.2
35     5.5
36        0
37        0
38     0.9
39    11.0
40        0
41     4.2
42        0
43     2.8
44     0.7
45        0
46    19.5
47        0
48     6.2
49     3.5
Name: resolution_time, dtype: object

In [15]:
df["resolution_time"]=pd.to_numeric(df["resolution_time"],errors="coerce")

In [16]:
Mean_resolution=df["resolution_time"].mean().round(2)

In [17]:
category_wise_mean=df.groupby("category")["resolution_time"].mean().round(2)

In [18]:
agent_value_counts=df["assigned_agent"].value_counts()

In [19]:
df.sort_values("resolution_time")

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
26,TCK-1027,Abhishek Patel,Login,Low,Resolved,Bob Jones,0.3
8,TCK-1009,Rahul Nair,Login,Medium,Resolved,Charlie Brown,0.5
44,TCK-1045,Vikram Patel,Login,Critical,Closed,Diana Prince,0.7
20,TCK-1021,Nikhil Joshi,Login,High,Resolved,Alice Smith,0.8
38,TCK-1039,Ashish Banerjee,Login,Medium,Resolved,Charlie Brown,0.9
14,TCK-1015,Karan Malhotra,Login,Critical,Closed,Diana Prince,1.0
32,TCK-1033,Varun Pillai,Login,High,Resolved,Charlie Brown,1.1
2,TCK-1003,Rohan Gupta,Login,Low,Resolved,Charlie Brown,1.2
5,TCK-1006,Neha Verma,Account,Low,Closed,Alice Smith,2.0
23,TCK-1024,Sunita Sharma,Account,Low,Resolved,Charlie Brown,2.5
43,TCK-1044,Ananya Sharma,Technical,Medium,Resolved,Charlie Brown,2.8
13,TCK-1014,Divya Das,Technical,Medium,Resolved,Charlie Brown,3.1
49,TCK-1050,Kavita Menon,Technical,Low,Closed,Diana Prince,3.5
30,TCK-1031,Kunal Nair,Payment,Low,Closed,Alice Smith,3.8
19,TCK-1020,Deepika Roy,Technical,Low,Closed,Diana Prince,4.0
41,TCK-1042,Neha Ghosh,Account,High,Resolved,Bob Jones,4.2
0,TCK-1001,Aarav Sharma,Payment,Medium,Resolved,Alice Smith,4.5
18,TCK-1019,Alok Banerjee,Payment,Critical,Resolved,Charlie Brown,5.0
35,TCK-1036,Shruti Sen,Account,Medium,Closed,Alice Smith,5.5
11,TCK-1012,Pooja Menon,Account,High,Resolved,Bob Jones,6.0
48,TCK-1049,Rahul Nair,Payment,Critical,Resolved,Charlie Brown,6.2
24,TCK-1025,Manoj Verma,Payment,Medium,Closed,Diana Prince,7.1
29,TCK-1030,Ritu Singh,Account,Critical,Resolved,Diana Prince,9.4
39,TCK-1040,Kriti Roy,Course,Low,Closed,Diana Prince,11.0
9,TCK-1010,Kavita Joshi,Course,Low,Closed,Diana Prince,12.5
27,TCK-1028,Pallavi Rao,Course,High,Resolved,Charlie Brown,15.0
16,TCK-1017,Arjun Mehta,Refund,Low,Resolved,Bob Jones,18.2
46,TCK-1047,Amit Gupta,Refund,Low,Resolved,Bob Jones,19.5
4,TCK-1005,Vikram Singh,Refund,Critical,Resolved,Diana Prince,24.0
34,TCK-1035,Tarun Malhotra,Refund,Critical,Resolved,Diana Prince,30.2
1,TCK-1002,Priya Patel,Technical,High,In Progress,Bob Jones,NaN
3,TCK-1004,Ananya Iyer,Course,Medium,Open,Unassigned,NaN
6,TCK-1007,Amit Kumar,Payment,High,In Progress,Bob Jones,NaN
7,TCK-1008,Sneha Reddy,Technical,Critical,Open,Unassigned,NaN
10,TCK-1011,Manish Rao,Refund,Medium,In Progress,Alice Smith,NaN
12,TCK-1013,Suresh Pillai,Payment,Low,Open,Unassigned,NaN
15,TCK-1016,Meera Sen,Course,High,In Progress,Alice Smith,NaN
17,TCK-1018,Tanvi Kapoor,Account,Medium,Open,Unassigned,NaN
21,TCK-1022,Swati Ghosh,Course,Medium,In Progress,Bob Jones,NaN
22,TCK-1023,Rajesh Kumar,Refund,High,Open,Unassigned,NaN
25,TCK-1026,Geeta Iyer,Technical,Critical,In Progress,Alice Smith,NaN
28,TCK-1029,Sanjay Gupta,Refund,Medium,Open,Unassigned,NaN
31,TCK-1032,Nisha Menon,Technical,Medium,In Progress,Bob Jones,NaN
33,TCK-1034,Payal Das,Course,Low,Open,Unassigned,NaN
36,TCK-1037,Vineet Mehta,Payment,High,In Progress,Bob Jones,NaN
37,TCK-1038,Pooja Kapoor,Technical,Critical,Open,Unassigned,NaN
40,TCK-1041,Siddharth Joshi,Refund,Medium,In Progress,Alice Smith,NaN
42,TCK-1043,Rohit Kumar,Payment,Low,Open,Unassigned,NaN
45,TCK-1046,Priya Rao,Course,High,In Progress,Alice Smith,NaN
47,TCK-1048,Sneha Singh,Account,Medium,Open,Unassigned,NaN

In [20]:
df[df["resolution_time"]==df["resolution_time"].max()]

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
34,TCK-1035,Tarun Malhotra,Refund,Critical,Resolved,Diana Prince,30.2

In [21]:
summary_data={"Mean_Resolution":Mean_resolution,
              "Max_Resolution_time":df["resolution_time"].max(),
              "Min_Resolution_time":df["resolution_time"].min(),
              "Total_Tickets" : len(df),
              "value_counts_category" : value_counts_category,
              "value_counts_priority":value_counts_category,
              "value_counts_status":value_counts_category,
              "category_wise_mean" :category_wise_mean,
              "agent_value_counts":agent_value_counts}

summary_df=pd.DataFrame(list(summary_data.items()),columns=["Metric" , "Value"])
print(summary_df)

NameError: name 'value_counts_category' is not defined

In [ ]:
summary_df.to_csv("summary_Report.csv" , index=False)